using System.Collections.Generic;
using KRPC.Service.KRPC;
using KRPC.Service.Messages;
using NUnit.Framework;
using Type = KRPC.Service.KRPC.Type;

namespace KRPC.Test.Service.KRPC
{
    /// <summary>
    /// Golden tests for the expression trees generated by the server side
    /// expression API, using ExpressionTreePrinter dumps. These verify the
    /// exact tree structure the factories emit — including the direct method
    /// call emission with its game scene and null return value checks, numeric
    /// promotion, and the rewriting of break/continue/return markers — without
    /// depending on the compiled IL.
    /// </summary>
    [TestFixture]
    public class ExpressionTreePrinterTest
    {
        static ProcedureCall BuildProcedureCall (string procedure, params Argument[] args)
        {
            var call = new ProcedureCall ("TestService", procedure);
            foreach (var arg in args)
                call.Arguments.Add (arg);
            return call;
        }

        static void Check (string expected, Expression expression)
        {
            Assert.AreEqual (expected, ExpressionTreePrinter.Print (expression));
        }

        [Test]
        public void NumericPromotion ()
        {
            Check (
                "Add<Double>\n" +
                "  Convert<Double>\n" +
                "    Constant<Int32> 1\n" +
                "  Constant<Double> 2.5\n",
                Expression.Add (Expression.ConstantInt (1), Expression.ConstantDouble (2.5)));
        }

        [Test]
        public void CallValueReturn ()
        {
            // A value typed return needs no null check after the direct call
            var obj = new global::KRPC.Test.Service.TestService.TestClass ("foo");
            Check (
                "Block<Int32>\n" +
                "  Call<Void> static Services.CheckExpressionGameScene\n" +
                "    Constant<ProcedureSignature> TestService.TestClass_get_IntProperty\n" +
                "  Call<Int32> TestClass.get_IntProperty\n" +
                "    Constant<TestClass> <TestClass>\n",
                Expression.Call (BuildProcedureCall ("TestClass_get_IntProperty", new Argument (0, obj))));
        }

        [Test]
        public void CallReferenceReturn ()
        {
            // A non-nullable reference typed return is checked for null on every
            // evaluation
            var obj = new global::KRPC.Test.Service.TestService.TestClass ("foo");
            Check (
                "Block<String> (returnValue#0)\n" +
                "  Call<Void> static Services.CheckExpressionGameScene\n" +
                "    Constant<ProcedureSignature> TestService.TestClass_FloatToString\n" +
                "  Assign<String>\n" +
                "    Parameter<String> returnValue#0\n" +
                "    Call<String> TestClass.FloatToString\n" +
                "      Constant<TestClass> <TestClass>\n" +
                "      Constant<Single> 0.5\n" +
                "  Call<Void> static Services.CheckExpressionReturnValue\n" +
                "    Constant<ProcedureSignature> TestService.TestClass_FloatToString\n" +
                "    Parameter<String> returnValue#0\n" +
                "  Parameter<String> returnValue#0\n",
                Expression.Call (BuildProcedureCall (
                    "TestClass_FloatToString", new Argument (0, obj), new Argument (1, 0.5f))));
        }

        [Test]
        public void CallVoidReturn ()
        {
            Check (
                "Block<Void>\n" +
                "  Call<Void> static Services.CheckExpressionGameScene\n" +
                "    Constant<ProcedureSignature> TestService.ProcedureSingleOptionalArgNoReturn\n" +
                "  Call<Void> static TestService.ProcedureSingleOptionalArgNoReturn\n" +
                "    Constant<String> \"foo\"\n",
                Expression.Call (BuildProcedureCall ("ProcedureSingleOptionalArgNoReturn")));
        }

        [Test]
        public void CallPerElement ()
        {
            // The function parameter provides the instance argument of the call
            var param = Expression.Parameter ("x", Type.ClassType ("TestService", "TestClass"));
            var call = Expression.CallWithArguments (
                BuildProcedureCall ("TestClass_FloatToString", new Argument (1, 0.5f)),
                new Dictionary<int, Expression> { { 0, param } });
            Check (
                "Lambda<Func<TestClass, String>> (x#0)\n" +
                "  Label<String> label#0\n" +
                "    Block<String> (returnValue#1)\n" +
                "      Call<Void> static Services.CheckExpressionGameScene\n" +
                "        Constant<ProcedureSignature> TestService.TestClass_FloatToString\n" +
                "      Assign<String>\n" +
                "        Parameter<String> returnValue#1\n" +
                "        Call<String> TestClass.FloatToString\n" +
                "          Parameter<TestClass> x#0\n" +
                "          Constant<Single> 0.5\n" +
                "      Call<Void> static Services.CheckExpressionReturnValue\n" +
                "        Constant<ProcedureSignature> TestService.TestClass_FloatToString\n" +
                "        Parameter<String> returnValue#1\n" +
                "      Parameter<String> returnValue#1\n",
                Expression.Function (new List<Expression> { param }, call));
        }

        [Test]
        public void Statements ()
        {
            // While desugars to a loop over a conditional; the break marker in the
            // body is rewritten to a goto targeting the loop's break label
            var i = Expression.Variable ("i", Type.Int ());
            var body = Expression.Block (new List<Expression> {
                Expression.IfThen (
                    Expression.GreaterThan (i, Expression.ConstantInt (10)),
                    Expression.Break ()),
                Expression.Assign (i, Expression.Add (i, Expression.ConstantInt (1)))
            });
            Check (
                "Block<Int32> (i#0)\n" +
                "  Assign<Int32>\n" +
                "    Parameter<Int32> i#0\n" +
                "    Constant<Int32> 0\n" +
                "  Loop<Void> break:label#0 continue:label#1\n" +
                "    Conditional<Void>\n" +
                "      Constant<Boolean> true\n" +
                "      Block<Void>\n" +
                "        Block<Int32>\n" +
                "          Conditional<Void>\n" +
                "            GreaterThan<Boolean>\n" +
                "              Parameter<Int32> i#0\n" +
                "              Constant<Int32> 10\n" +
                "            Goto<Void> Break label#0\n" +
                "            Default<Void>\n" +
                "          Assign<Int32>\n" +
                "            Parameter<Int32> i#0\n" +
                "            Add<Int32>\n" +
                "              Parameter<Int32> i#0\n" +
                "              Constant<Int32> 1\n" +
                "      Goto<Void> Break label#0\n" +
                "  Parameter<Int32> i#0\n",
                Expression.BlockWithVariables (
                    new List<Expression> { i },
                    new List<Expression> {
                        Expression.Assign (i, Expression.ConstantInt (0)),
                        Expression.While (Expression.ConstantBool (true), body),
                        i
                    }));
        }

        [Test]
        public void FunctionWithReturn ()
        {
            // An early return becomes a marker (rewritten to a goto); the function's
            // final return statement compiles to a plain trailing value, which types
            // the label the markers jump to
            var x = Expression.Parameter ("x", Type.Int ());
            var body = Expression.Block (new List<Expression> {
                Expression.IfThen (
                    Expression.LessThan (x, Expression.ConstantInt (0)),
                    Expression.Return (Expression.ConstantInt (0))),
                x
            });
            Check (
                "Lambda<Func<Int32, Int32>> (x#0)\n" +
                "  Label<Int32> label#0\n" +
                "    Block<Int32>\n" +
                "      Conditional<Void>\n" +
                "        LessThan<Boolean>\n" +
                "          Parameter<Int32> x#0\n" +
                "          Constant<Int32> 0\n" +
                "        Block<Void>\n" +
                "          Goto<Void> Return label#0\n" +
                "            Constant<Int32> 0\n" +
                "        Default<Void>\n" +
                "      Parameter<Int32> x#0\n",
                Expression.Function (new List<Expression> { x }, body));
        }

        [Test]
        public void ForEachLoop ()
        {
            // ForEach desugars to an enumerator loop. The loop variable is not
            // declared by ForEach itself; the enclosing block must declare it
            var x = Expression.Variable ("x", Type.Int ());
            var total = Expression.Variable ("total", Type.Int ());
            var list = Expression.CreateList (new List<Expression> {
                Expression.ConstantInt (1),
                Expression.ConstantInt (2)
            });
            Check (
                "Block<Int32> (total#0, x#1)\n" +
                "  Block<Void> (enumerator#2)\n" +
                "    Assign<IEnumerator<Int32>>\n" +
                "      Parameter<IEnumerator<Int32>> enumerator#2\n" +
                "      Call<IEnumerator<Int32>> IEnumerable<Int32>.GetEnumerator\n" +
                "        New<List<Int32>>\n" +
                "          NewArrayInit<Int32[]>\n" +
                "            Constant<Int32> 1\n" +
                "            Constant<Int32> 2\n" +
                "    Try<Void>\n" +
                "      Loop<Void> break:label#0 continue:label#1\n" +
                "        Conditional<Void>\n" +
                "          Call<Boolean> IEnumerator.MoveNext\n" +
                "            Parameter<IEnumerator<Int32>> enumerator#2\n" +
                "          Block<Void>\n" +
                "            Assign<Int32>\n" +
                "              Parameter<Int32> x#1\n" +
                "              MemberAccess<Int32> IEnumerator<Int32>.Current\n" +
                "                Parameter<IEnumerator<Int32>> enumerator#2\n" +
                "            Block<Void>\n" +
                "              Assign<Int32>\n" +
                "                Parameter<Int32> total#0\n" +
                "                Add<Int32>\n" +
                "                  Parameter<Int32> total#0\n" +
                "                  Parameter<Int32> x#1\n" +
                "          Goto<Void> Break label#0\n" +
                "      Finally\n" +
                "        Call<Void> IDisposable.Dispose\n" +
                "          Parameter<IEnumerator<Int32>> enumerator#2\n" +
                "  Parameter<Int32> total#0\n",
                Expression.BlockWithVariables (
                    new List<Expression> { total, x },
                    new List<Expression> {
                        Expression.ForEach (x, list, Expression.Assign (total, Expression.Add (total, x))),
                        total
                    }));
        }

        [Test]
        public void ConditionalExpr ()
        {
            Check (
                "Conditional<String>\n" +
                "  Constant<Boolean> true\n" +
                "  Constant<String> \"a\"\n" +
                "  Constant<String> \"b\"\n",
                Expression.Conditional (
                    Expression.ConstantBool (true),
                    Expression.ConstantString ("a"),
                    Expression.ConstantString ("b")));
        }
    }
}
