name: ksp-lib
description: Fetch stripped KSP libraries
inputs:
  version:
    description: "Version of the game, e.g. 1.12.5"
    required: true
  path:
    description: "Path to extract the contents of the archive into. Defaults to lib/ksp"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: download
      run: |
        import urllib.request
        urllib.request.urlretrieve("https://github.com/krpc/ksp-lib/raw/main/ksp/ksp-${{ inputs.version }}.zip", "ksp-${{ inputs.version }}.zip")
      shell: python
    - name: extract
      run: |
        import shutil
        path = "${{ inputs.path }}"
        if len(path) == 0:
            path = "lib/ksp"
        print("path =", path)
        shutil.unpack_archive("ksp-${{ inputs.version }}.zip", path)
      shell: python
    - name: cleanup
      run: |
        import os
        os.unlink("ksp-${{ inputs.version }}.zip")
      shell: python
