package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'SpaceCenter',
    srcs = [
        '//service/SpaceCenter:kRPCSpaceCenter',
        '//service/SpaceCenter:ServiceDefinitions'
    ]
)

filegroup(
    name = 'KerbalAlarmClock',
    srcs = [
        '//service/KerbalAlarmClock:kRPCKerbalAlarmClock',
        '//service/KerbalAlarmClock:ServiceDefinitions'
    ]
)

filegroup(
    name = 'InfernalRobotics',
    srcs = [
        '//service/InfernalRobotics:kRPCInfernalRobotics',
        '//service/InfernalRobotics:ServiceDefinitions'
    ]
)
