inputs:
  packages:
    required: true
runs:
  using: composite
  steps:
    - name: cache-key
      id: cache-key
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        commit=$(vcpkg version | head -n1 | awk '{print $NF}')
        info=$(printf '%s\n' vcpkg linux "$ImageOS" "$ImageVersion" "$commit" "$PACKAGES")
        echo 'cache key inputs:'
        printf '%s\n' "$info" | sed 's/^/  /'
        hash=$(printf '%s' "$info" | sha256sum | cut -d' ' -f1)
        echo "cache key: vcpkg-$hash"
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
    - name: cache-vcpkg
      uses: actions/cache@v5
      with:
        path: ~/.cache/vcpkg
        key: vcpkg-${{ steps.cache-key.outputs.hash }}
