load('/tools/build/csharp', 'csharp_reference')

package(default_visibility = ['//visibility:public'])

csharp_reference(name = 'UnityEngine', file = ':ksp/KSP_Data/Managed/UnityEngine.dll')
csharp_reference(name = 'Assembly-CSharp', file = ':ksp/KSP_Data/Managed/Assembly-CSharp.dll')
csharp_reference(name = 'Assembly-CSharp-firstpass', file = ':ksp/KSP_Data/Managed/Assembly-CSharp-firstpass.dll')
csharp_reference(name = 'TDx.TDxInput', file = ':ksp/KSP_Data/Managed/TDx.TDxInput.dll')

csharp_reference(name = 'mscorlib', file = ':ksp/KSP_Data/Managed/mscorlib.dll')
csharp_reference(name = 'System', file = ':ksp/KSP_Data/Managed/System.dll')
csharp_reference(name = 'System.Core', file = ':ksp/KSP_Data/Managed/System.Core.dll')
csharp_reference(name = 'System.Xml', file = ':ksp/KSP_Data/Managed/System.Xml.dll')
csharp_reference(name = 'System.Xml.Linq', file = ':ksp/KSP_Data/Managed/System.Xml.Linq.dll')
