using System;
using KRPC.Service;
using KRPC.Service.Attributes;
using KRPC.SpaceCenter.ExtensionMethods;
using KRPC.Utils;

namespace KRPC.SpaceCenter.Services.Parts
{
    /// <summary>
    /// A solar panel. Obtained by calling <see cref="Part.SolarPanel"/>.
    /// </summary>
    [KRPCClass (Service = "SpaceCenter", GameScene = GameScene.Flight)]
    public class SolarPanel : Equatable<SolarPanel>, IGameObjectState
    {
        ModuleRef panelRef;

        internal static bool Is (Part part)
        {
            return part.InternalPart.HasModule<ModuleDeployableSolarPanel> ();
        }

        internal SolarPanel (Part part)
        {
            Part = part;
            panelRef = ModuleRef.ForType<ModuleDeployableSolarPanel> (part.InternalPart);
            if (panelRef.Find (part.InternalPart) == null)
                throw new ArgumentException ("Part is not a solar panel");
        }

        ModuleDeployableSolarPanel InternalPanel {
            get { return (ModuleDeployableSolarPanel)panelRef.Get (Part.InternalPart); }
        }

        /// <summary>
        /// What the game holds for the solar panel: the state of the part
        /// carrying it, or destroyed once that part no longer has the module.
        /// </summary>
        public GameObjectState GameObjectState {
            get { return panelRef.StateOn (Part); }
        }

        /// <summary>
        /// Returns true if the objects are equal.
        /// </summary>
        public override bool Equals (SolarPanel other)
        {
            return !ReferenceEquals (other, null) && Part == other.Part && panelRef == other.panelRef;
        }

        /// <summary>
        /// Hash code for the object.
        /// </summary>
        public override int GetHashCode ()
        {
            return Hash.Of (Part).And (panelRef);
        }

        /// <summary>
        /// The part object for this solar panel.
        /// </summary>
        [KRPCProperty (GameScene = GameScene.Flight | GameScene.Editor)]
        public Part Part { get; private set; }

        /// <summary>
        /// Whether the solar panel is deployable.
        /// </summary>
        [KRPCProperty (GameScene = GameScene.Flight | GameScene.Editor)]
        public bool Deployable {
            get {
                return
                    InternalPanel.Events ["Extend"].active || InternalPanel.Events ["Retract"].active ||
                    InternalPanel.deployState == ModuleDeployablePart.DeployState.EXTENDING ||
                    InternalPanel.deployState == ModuleDeployablePart.DeployState.RETRACTING;
            }
        }

        /// <summary>
        /// Whether the solar panel is extended.
        /// </summary>
        [KRPCProperty]
        public bool Deployed {
            get {
                return
                InternalPanel.deployState == ModuleDeployablePart.DeployState.EXTENDED ||
                InternalPanel.deployState == ModuleDeployablePart.DeployState.EXTENDING;
            }
            set {
                if (!Deployable)
                    throw new InvalidOperationException ("Solar panel is not deployable");
                if (value)
                    InternalPanel.Extend ();
                else
                    InternalPanel.Retract ();
            }
        }

        /// <summary>
        /// The current state of the solar panel.
        /// </summary>
        [KRPCProperty]
        public DeployableState State {
            get { return InternalPanel.deployState.ToDeployableState (); }
        }

        /// <summary>
        /// The current amount of energy being generated by the solar panel, in
        /// units of charge per second.
        /// </summary>
        [KRPCProperty]
        public float EnergyFlow {
            get { return InternalPanel.flowRate; }
        }

        /// <summary>
        /// The current amount of sunlight that is incident on the solar panel,
        /// as a percentage. A value between 0 and 1.
        /// </summary>
        [KRPCProperty]
        public float SunExposure {
            get { return InternalPanel.sunAOA; }
        }
    }
}
