#!/usr/bin/env python3

"""Live-build and serve the documentation website.

Run via ``bazel run //doc:serve`` (optionally ``-- --port N``). Builds the
``//doc:srcs`` staged doc tree, serves it with sphinx-autobuild, and rebuilds
whenever a documentation source changes.

Rebuilding is two-layered because the doc sources are partly generated by Bazel
(the API docs, changelog and conf.py): watchdog watches the real source dirs and
re-runs ``bazel build //doc:srcs`` to regenerate the staged tree, and
sphinx-autobuild watches that staged tree to rebuild the HTML and live-reload the
browser.
"""

import argparse
import filecmp
import os
import shutil
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import webbrowser

from watchdog.events import FileSystemEventHandler
from watchdog.observers import Observer

# Kept out of bazel-bin/doc/serve* so they don't collide with the `serve` binary
# artifact that `bazel run //doc:serve` produces at bazel-bin/doc/serve.
SRC = os.path.join("bazel-bin", "doc", "srcs")
STAGE = os.path.join("bazel-bin", "doc", "srcs-stage")
OUT = os.path.join("bazel-bin", "doc", "srcs-serve-out")


def targets_to_paths(targets):
    """Converts a list of bazel targets to a list of source file paths"""
    result = []
    for target in targets:
        if target.startswith("//"):
            path = target[2:].replace(":", "/")
            if path[0] == "/":
                path = path[1:]
            if os.path.exists(path):
                result.append(path)
    return result


def source_dependencies():
    """The workspace source files that the staged docs are built from"""
    output = subprocess.check_output(
        ["bazel", "query", "kind(file, deps(//doc:srcs))"]
    ).decode()
    targets = [line.strip() for line in output.split("\n") if line.strip()]
    return set(targets_to_paths(targets))


def update_stage(strict=False):
    """Rebuild the staged doc tree and mirror it into the stage directory.

    The ``//doc:srcs`` outputs are symlinks, so the staged copy is dereferenced
    into plain files that sphinx-autobuild can watch and read.

    A failed rebuild (e.g. a source file saved mid-edit) is not fatal while
    watching: keep serving the previous build and try again on the next change.
    An exception here would otherwise kill the watchdog emitter thread and
    silently stop all future rebuilds. The initial build is strict so a broken
    checkout doesn't silently serve empty or stale docs.
    """
    try:
        subprocess.check_call(["bazel", "build", "//doc:srcs"])
    except subprocess.CalledProcessError:
        if strict:
            raise
        print("Rebuild failed; keeping previously staged files")
        return
    if not os.path.exists(STAGE):
        os.makedirs(STAGE)

    # Remove files from stage directory that are not in src directory
    for basepath, _, filenames in os.walk(STAGE):
        for filename in filenames:
            path = os.path.relpath(os.path.join(basepath, filename), STAGE)
            if not os.path.exists(os.path.join(SRC, path)):
                print("Removing", path)
                os.unlink(os.path.join(STAGE, path))

    # Update stale files in stage directory
    for basepath, _, filenames in os.walk(SRC):
        for filename in filenames:
            path = os.path.relpath(os.path.join(basepath, filename), SRC)
            srcpath = os.path.join(SRC, path)
            stagepath = os.path.join(STAGE, path)
            if not os.path.exists(stagepath):
                print("Staging new file", path)
                if not os.path.exists(os.path.dirname(stagepath)):
                    os.makedirs(os.path.dirname(stagepath))
                shutil.copy(srcpath, stagepath)
            elif not filecmp.cmp(srcpath, stagepath):
                print("Updating file", path)
                os.unlink(stagepath)
                shutil.copy(srcpath, stagepath)


class UpdateStagedFiles(FileSystemEventHandler):
    """Rebuilds via bazel then updates the stage directory on any change"""

    def on_modified(self, event):
        update_stage()


def watch_roots(dependencies):
    """The top-level directories to watch, with nested paths collapsed"""
    watch_dirs = sorted(
        {os.path.dirname(p) for p in dependencies if os.path.dirname(p)}
    )
    roots = []
    for directory in watch_dirs:
        if not any(directory == r or directory.startswith(r + os.sep) for r in roots):
            roots.append(directory)
    return roots


def open_browser_when_ready(url, is_alive, timeout=120.0, interval=0.5):
    """Open ``url`` in a browser once the server responds, in the background.

    Polls ``url`` until it serves a response, then opens it once. Stops early if
    the server dies (``is_alive`` returns False) or the timeout elapses. Runs in
    a daemon thread so it never delays shutdown, and a browser that fails to
    launch (e.g. a headless host) is ignored.
    """

    def wait_and_open():
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if not is_alive():
                return
            try:
                urllib.request.urlopen(url, timeout=interval).close()
            except urllib.error.HTTPError:
                pass  # a response (even an error page) means the server is up
            except OSError:
                time.sleep(interval)
                continue
            print("Opening", url)
            try:
                webbrowser.open(url)
            except webbrowser.Error:
                pass
            return

    threading.Thread(target=wait_and_open, daemon=True).start()


def serve(port, open_browser=True):
    """Serve the staged docs and rebuild on change; blocks until interrupted.

    sphinx-autobuild rebuilds by running ``sphinx build`` under this
    interpreter, so the sphinx extensions (bundled as runfiles of this binary)
    are made importable to that child process via PYTHONPATH.
    """
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(p for p in sys.path if p)
    # The version switcher fetches switcher.json from the published site, which
    # this local build cannot reach; signal conf.py to drop it.
    env["KRPC_DOCS_LOCAL_SERVE"] = "1"
    server = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "sphinx_autobuild",
            "-W",
            "-n",
            "-T",
            "--host",
            "0.0.0.0",
            "--port",
            str(port),
            STAGE,
            OUT,
        ],
        env=env,
    )

    # Point the browser at localhost rather than the 0.0.0.0 bind address, which
    # is not a usable URL on every platform.
    if open_browser:
        open_browser_when_ready(
            "http://localhost:%d" % port, lambda: server.poll() is None
        )

    handler = UpdateStagedFiles()
    observer = Observer()
    for path in watch_roots(source_dependencies()):
        if not os.path.isdir(path):
            continue
        try:
            observer.schedule(handler, path, recursive=True)
        except OSError as exc:
            print("Skipping watch on", path, "-", exc)
    observer.start()

    # Wait for the server to exit: either it dies on its own (crash, port in
    # use) or Ctrl-C lands here as KeyboardInterrupt. In both cases shut down the
    # file watcher and make sure sphinx-autobuild is dead. The terminal delivers
    # SIGINT to sphinx-autobuild too, but its graceful shutdown can hang, so
    # escalate explicitly: SIGTERM, then SIGKILL if it still hasn't exited.
    exit_code = 1
    try:
        exit_code = server.wait()
    except KeyboardInterrupt:
        print("Interrupted, shutting down")
    finally:
        observer.stop()
        if server.poll() is None:
            server.terminate()
            try:
                exit_code = server.wait(timeout=5)
            except subprocess.TimeoutExpired:
                print("sphinx-autobuild did not exit after SIGTERM, killing it")
                server.kill()
                exit_code = server.wait()
        observer.join()
    return exit_code


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--port", type=int, default=8080, help="port to serve on (default 8080)"
    )
    parser.add_argument(
        "--no-browser",
        dest="open_browser",
        action="store_false",
        help="do not open a web browser once the server is ready",
    )
    args = parser.parse_args()

    # Under `bazel run` the process starts in the runfiles tree; move to the
    # workspace root so the nested bazel calls and bazel-bin paths resolve.
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if not workspace:
        sys.exit("This tool must be run via `bazel run //doc:serve`.")
    os.chdir(workspace)

    # Build and stage the docs before serving; a failure here is fatal.
    update_stage(strict=True)
    return serve(args.port, open_browser=args.open_browser)


if __name__ == "__main__":
    sys.exit(main())
