exports_files ([
    'mono-4.5/mscorlib.dll',
    'mono-4.5/System.dll',
    'mono-4.5/System.Core.dll',
    'mono-4.5/Facades/System.Runtime.dll',
    'mono-4.5/Facades/System.IO.dll',
    'mono-4.5/System.Xml.dll',
    'mono-4.5/System.Xml.Linq.dll',

    'ksp/KSP_Data/Managed/Assembly-CSharp.dll',
    'ksp/KSP_Data/Managed/Assembly-CSharp-firstpass.dll',
    'ksp/KSP_Data/Managed/UnityEngine.dll',
    'ksp/KSP_Data/Managed/UnityEngine.UI.dll',
    'ksp/KSP_Data/Managed/TDx.TDxInput.dll',
    'ksp/KSP_Data/Managed/KSPUtil.dll',

    'ksp/KSP_Data/Managed/mscorlib.dll',
    'ksp/KSP_Data/Managed/System.dll',
    'ksp/KSP_Data/Managed/System.Core.dll',
    'ksp/KSP_Data/Managed/System.Xml.dll',
    'ksp/KSP_Data/Managed/System.Xml.Linq.dll'
])
