runs:
  using: composite
  steps:
    - name: restore-bazel-cache
      id: bazel-cache
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/bazel
        key: bazel-cache-${{ hashFiles('WORKSPACE') }}
    - name: bazel-fetch
      if: steps.bazel-cache.outputs.cache-hit != 'true'
      run: bazel fetch //...
      shell: bash
    - name: save-bazel-cache
      if: steps.bazel-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/bazel
        key: bazel-cache-${{ hashFiles('WORKSPACE') }}
