runs:
  using: composite
  steps:
    - run: |
        tools/github-actions/set-version.py
        rm -f lib/mono-4.5
        ln -s /usr/lib/mono/4.5 lib/mono-4.5
        rm -f lib/ksp
        ln -s /usr/local/lib/ksp lib/ksp
      shell: bash
